-- Category Analysis

-- How much total revenue is generated by each category
SELECT
    c.category_id,
    c.category_name,
    ROUND(SUM((od.quantity * od.unit_price) - od.discount), 2) AS revenue
FROM order_details od
JOIN products p 
    ON p.product_id = od.product_id
JOIN categories c 
    ON c.category_id = p.category_id
JOIN orders o 
    ON o.order_id = od.order_id
WHERE o.order_status = 'Delivered'
GROUP BY c.category_id, c.category_name
ORDER BY revenue DESC;

-- Which category appears in the highest number of distinct delivered orders.alter
SELECT
    c.category_id,
    c.category_name,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM order_details od
JOIN orders o 
    ON o.order_id = od.order_id
JOIN products p 
    ON p.product_id = od.product_id
JOIN categories c 
    ON c.category_id = p.category_id
WHERE o.order_status = 'Delivered'
GROUP BY c.category_id, c.category_name
ORDER BY total_orders DESC;

-- Average Product Price by Category
SELECT 
c.category_id,
c.category_name,
ROUND(AVG(PRICE),2) AS average_price
FROM products AS P
INNER JOIN categories AS c ON p.category_id=c.category_id
GROUP BY c.category_id,c.category_name
ORDER BY average_price DESC;

-- Category Cancellation Rate
WITH total_orders AS (
    SELECT 
        c.category_id,
        COUNT(DISTINCT o.order_id) AS total_orders
    FROM order_details od
    JOIN products p 
        ON p.product_id = od.product_id
    JOIN categories c 
        ON p.category_id = c.category_id
    JOIN orders o 
        ON o.order_id = od.order_id
    GROUP BY c.category_id
),

cancelled_orders AS (
    SELECT
        c.category_id,
        COUNT(DISTINCT o.order_id) AS cancelled_orders
    FROM order_details od
    JOIN products p 
        ON p.product_id = od.product_id
    JOIN categories c 
        ON p.category_id = c.category_id
    JOIN orders o 
        ON o.order_id = od.order_id
    WHERE o.order_status = 'Cancelled'
    GROUP BY c.category_id
)

SELECT
    t.category_id,
    ROUND((COALESCE(c.cancelled_orders, 0) / t.total_orders) * 100, 2) 
        AS cancellation_rate
FROM total_orders t
LEFT JOIN cancelled_orders c 
    ON t.category_id = c.category_id
ORDER BY cancellation_rate DESC;

-- Quantity Contribution by Category
SELECT
    c.category_id,
    c.category_name,
    SUM(od.quantity) AS category_quantity,
    ROUND(
        (SUM(od.quantity) * 100.0) 
        / SUM(SUM(od.quantity)) OVER (),
    2) AS quantity_percentage
FROM order_details od
JOIN orders o 
    ON o.order_id = od.order_id
JOIN products p 
    ON p.product_id = od.product_id
JOIN categories c 
    ON c.category_id = p.category_id
WHERE o.order_status = 'Delivered'
GROUP BY c.category_id, c.category_name
ORDER BY quantity_percentage DESC;
