-- Category Analysis

-- How much total revenue is generated by each category
SELECT
    c.category_id,
    c.category_name,
    ROUND(SUM((od.quantity * od.unit_price) - od.discount), 2) AS revenue
FROM order_details od
JOIN products p 
    ON p.product_id = od.product_id
JOIN categories c 
    ON c.category_id = p.category_id
JOIN orders o 
    ON o.order_id = od.order_id
WHERE o.order_status = 'Delivered'
GROUP BY c.category_id, c.category_name
ORDER BY revenue DESC;

-- Which category appears in the highest number of distinct delivered orders.alter
SELECT
    c.category_id,
    c.category_name,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM order_details od
JOIN orders o 
    ON o.order_id = od.order_id
JOIN products p 
    ON p.product_id = od.product_id
JOIN categories c 
    ON c.category_id = p.category_id
WHERE o.order_status = 'Delivered'
GROUP BY c.category_id, c.category_name
ORDER BY total_orders DESC;

-- Average Product Price by Category
SELECT 
c.category_id,
c.category_name,
ROUND(AVG(PRICE),2) AS average_price
FROM products AS P
INNER JOIN categories AS c ON p.category_id=c.category_id
GROUP BY c.category_id,c.category_name
ORDER BY average_price DESC;

-- Category Cancellation Rate
WITH total_orders AS (
    SELECT 
        c.category_id,
        COUNT(DISTINCT o.order_id) AS total_orders
    FROM order_details od
    JOIN products p 
        ON p.product_id = od.product_id
    JOIN categories c 
        ON p.category_id = c.category_id
    JOIN orders o 
        ON o.order_id = od.order_id
    GROUP BY c.category_id
),

cancelled_orders AS (
    SELECT
        c.category_id,
        COUNT(DISTINCT o.order_id) AS cancelled_orders
    FROM order_details od
    JOIN products p 
        ON p.product_id = od.product_id
    JOIN categories c 
        ON p.category_id = c.category_id
    JOIN orders o 
        ON o.order_id = od.order_id
    WHERE o.order_status = 'Cancelled'
    GROUP BY c.category_id
)

SELECT
    t.category_id,
    ROUND((COALESCE(c.cancelled_orders, 0) / t.total_orders) * 100, 2) 
        AS cancellation_rate
FROM total_orders t
LEFT JOIN cancelled_orders c 
    ON t.category_id = c.category_id
ORDER BY cancellation_rate DESC;

-- Quantity Contribution by Category
SELECT
    c.category_id,
    c.category_name,
    SUM(od.quantity) AS category_quantity,
    ROUND(
        (SUM(od.quantity) * 100.0) 
        / SUM(SUM(od.quantity)) OVER (),
    2) AS quantity_percentage
FROM order_details od
JOIN orders o 
    ON o.order_id = od.order_id
JOIN products p 
    ON p.product_id = od.product_id
JOIN categories c 
    ON c.category_id = p.category_id
WHERE o.order_status = 'Delivered'
GROUP BY c.category_id, c.category_name
ORDER BY quantity_percentage DESC;

CUSTOMER ANALYSIS

-- Top 10 Customers by Total Spending
SELECT
    c.customer_id,
    c.full_name,
    ROUND(SUM((od.quantity * od.unit_price) - od.discount), 2) AS total_spent
FROM customers c
JOIN orders o 
    ON o.customer_id = c.customer_id
JOIN order_details od 
    ON o.order_id = od.order_id
WHERE o.order_status = 'Delivered'
GROUP BY c.customer_id, c.full_name
ORDER BY total_spent DESC
LIMIT 10;


-- Repeat vs One-Time Customers
WITH table_1 AS (
    SELECT
        customer_id,
        COUNT(*) AS total_orders
    FROM orders
    WHERE order_status = 'Delivered'
    GROUP BY customer_id
)

SELECT
    SUM(CASE WHEN total_orders = 1 THEN 1 ELSE 0 END) AS one_time_customers,
    SUM(CASE WHEN total_orders > 1 THEN 1 ELSE 0 END) AS repeat_customers
FROM table_1;

-- Average Orders Per Customer
WITH table_1 AS (
    SELECT
        customer_id,
        COUNT(order_id) AS order_count
    FROM orders
    WHERE order_status = 'Delivered'
    GROUP BY customer_id
)

SELECT 
    ROUND(AVG(order_count), 2) AS avg_orders_per_customer
FROM table_1;

-- Revenue by City
SELECT
    c.city,
    ROUND(SUM((od.quantity * od.unit_price) - od.discount), 2) AS total_amount
FROM customers c
JOIN orders o 
    ON o.customer_id = c.customer_id
JOIN order_details od 
    ON od.order_id = o.order_id
WHERE o.order_status = 'Delivered'
GROUP BY c.city
ORDER BY total_amount DESC
LIMIT 1;

-- cancellation rate
SELECT
    customer_id,
    COUNT(*) AS cancelled_orders
FROM orders 
WHERE order_status = 'Cancelled'
GROUP BY customer_id
HAVING COUNT(*) > 2
ORDER BY cancelled_orders DESC;

-- Cancellation & Operations

-- Overall Cancellation Rate
SELECT
ROUND(
    COUNT(CASE WHEN order_status = 'Cancelled' THEN 1 END) 
    * 100.0
    / COUNT(DISTINCT order_id),
2) AS cancellation_rate
FROM orders;

-- Monthly Cancellation Trend
SELECT
    DATE_FORMAT(order_date, '%Y-%m') AS month,
    ROUND(
        COUNT(CASE WHEN order_status = 'Cancelled' THEN 1 END)
        * 100.0
        / COUNT(order_id),
    2) AS cancellation_rate
FROM orders
GROUP BY month
ORDER BY month;

-- Most Cancelled Products
SELECT
    p.product_id,
    p.product_name,
    SUM(od.quantity) AS cancelled_quantity
FROM order_details od
JOIN orders o 
    ON o.order_id = od.order_id
JOIN products p 
    ON p.product_id = od.product_id
WHERE o.order_status = 'Cancelled'
GROUP BY p.product_id, p.product_name
ORDER BY cancelled_quantity DESC
LIMIT 5;

-- Overall Average Delivery Time (All Delivered Orders)
SELECT
ROUND(AVG(DATEDIFF(delivered_date, order_date)), 2) AS avg_delivery_time
FROM orders
WHERE order_status = 'Delivered';

-- Late Delivery Analysis
SELECT
    order_id,
    order_date,
    delivered_date,
    DATEDIFF(delivered_date, order_date) AS delivery_days
FROM orders
WHERE order_status = 'Delivered'
AND DATEDIFF(delivered_date, order_date) > 5
ORDER BY delivery_days DESC;

Product Analysis

-- Top 10 Best-Selling Products
SELECT
    p.product_id,
    p.product_name,
    SUM(od.quantity) AS quantity_sold
FROM order_details od
JOIN orders o 
    ON o.order_id = od.order_id
JOIN products p 
    ON p.product_id = od.product_id
WHERE o.order_status = 'Delivered'
GROUP BY p.product_id, p.product_name
ORDER BY quantity_sold DESC
LIMIT 10;

-- products generate the highest revenue
SELECT
    p.product_id,
    p.product_name,
    ROUND(SUM((od.quantity * od.unit_price) - od.discount), 2) AS revenue
FROM order_details od
JOIN orders o 
    ON o.order_id = od.order_id
JOIN products p 
    ON p.product_id = od.product_id
WHERE o.order_status = 'Delivered'
GROUP BY p.product_id, p.product_name
ORDER BY revenue DESC
LIMIT 10;

-- products that are selling in high quantity but generating low revenue.
SELECT
    p.product_id,
    p.product_name,
    SUM(od.quantity) AS total_sold,
    ROUND(SUM((od.quantity * od.unit_price) - od.discount), 2) AS total_revenue
FROM order_details od
JOIN orders o 
    ON o.order_id = od.order_id
JOIN products p 
    ON p.product_id = od.product_id
WHERE o.order_status = 'Delivered'
GROUP BY p.product_id, p.product_name
ORDER BY total_sold DESC, total_revenue ASC;

-- products where the average discount given is higher than 20% of unit price.
SELECT
    p.product_id,
    p.product_name,
    ROUND(AVG(od.discount / od.unit_price), 2) AS average_discount_ratio
FROM order_details od 
JOIN orders o 
    ON o.order_id = od.order_id
JOIN products p 
    ON p.product_id = od.product_id
WHERE o.order_status = 'Delivered'
GROUP BY p.product_id, p.product_name
HAVING AVG(od.discount / od.unit_price) > 0.20;

-- Find products that were never sold (no order_details records).
SELECT 
    p.product_id,
    p.product_name
FROM products p
LEFT JOIN order_details od 
    ON p.product_id = od.product_id
WHERE od.product_id IS NULL;

-- SALES ANALYSIS

-- total revenue
SELECT 
    ROUND(SUM(od.quantity * od.unit_price), 2) AS total_revenue
FROM orders o
JOIN order_details od 
    ON o.order_id = od.order_id
WHERE o.order_status = 'Delivered';

-- Monthy Revenue
SELECT
    DATE_FORMAT(o.order_date, '%Y-%m') AS month,
    ROUND(
        SUM((od.quantity * od.unit_price) - od.discount),
    2) AS net_revenue
FROM orders o
JOIN order_details od 
    ON o.order_id = od.order_id
WHERE o.order_status = 'Delivered'
GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
ORDER BY month;

-- average order value
SELECT 
    ROUND(AVG(order_total), 2) AS AOV
FROM (
    SELECT 
        o.order_id,
        SUM((od.quantity * od.unit_price) - od.discount) AS order_total
    FROM orders o
    JOIN order_details od 
        ON o.order_id = od.order_id
    WHERE o.order_status = 'Delivered'
    GROUP BY o.order_id
) t;

-- Highest Sales Day
SELECT
    DAYNAME(o.order_date) AS day_name,
    ROUND(SUM((od.quantity * od.unit_price) - od.discount), 2) AS total_revenue
FROM orders o
JOIN order_details od 
    ON o.order_id = od.order_id
WHERE o.order_status = 'Delivered'
GROUP BY day_name
ORDER BY total_revenue DESC
LIMIT 1;

-- Top 10% Revenue Contribution
WITH order_revenue AS (
    SELECT 
        o.order_id,
        SUM((od.quantity * od.unit_price) - od.discount) AS revenue
    FROM orders o
    JOIN order_details od 
        ON o.order_id = od.order_id
    WHERE o.order_status = 'Delivered'
    GROUP BY o.order_id
),

ranked_orders AS (
    SELECT 
        order_id,
        revenue,
        ROW_NUMBER() OVER (ORDER BY revenue DESC) AS rn,
        COUNT(*) OVER () AS total_orders
    FROM order_revenue
)

SELECT 
    ROUND(
        SUM(CASE 
                WHEN rn <= CEIL(total_orders * 0.10) 
                THEN revenue 
            END)
        /
        SUM(revenue) * 100,
    2) AS top_10_percent_revenue_contribution
FROM ranked_orders;

 SHIPPER ANALYSIS

-- Orders Delivered by Shipper
SELECT
    s.shipper_id,
    s.shipper_name,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM orders o
JOIN shippers s 
    ON s.shipper_id = o.shipper_id
WHERE o.order_status = 'Delivered'
GROUP BY s.shipper_id, s.shipper_name
ORDER BY total_orders DESC;

-- Average Delivery Time
SELECT
    s.shipper_id,
    s.company_name,
    ROUND(AVG(DATEDIFF(o.delivered_date, o.order_date)), 2) AS avg_delivery_days
FROM orders o
JOIN shippers s 
    ON s.shipper_id = o.shipper_id
WHERE o.order_status = 'Delivered'
GROUP BY s.shipper_id, s.company_name
ORDER BY avg_delivery_days ASC;

-- Fastest Shipper
SELECT
    s.shipper_id,
    s.company_name,
    ROUND(AVG(DATEDIFF(o.delivered_date, o.order_date)), 2) AS average_time
FROM orders o
JOIN shippers s 
    ON s.shipper_id = o.shipper_id
WHERE o.order_status = 'Delivered'
GROUP BY s.shipper_id, s.company_name
ORDER BY average_time ASC
LIMIT 1;

-- Cancellation by Shipper
SELECT
    s.shipper_id,
    s.company_name,
    COUNT(DISTINCT o.order_id) AS cancelled_orders
FROM orders o
JOIN shippers s  
    ON s.shipper_id = o.shipper_id
WHERE o.order_status = 'Cancelled'
GROUP BY s.shipper_id, s.company_name
ORDER BY cancelled_orders DESC;

-- Shipper Performance Ranking
WITH avg_time AS (
    SELECT
        s.shipper_id,
        s.company_name,
        ROUND(AVG(DATEDIFF(o.delivered_date, o.order_date)), 2) AS average_time
    FROM orders o
    JOIN shippers s 
        ON s.shipper_id = o.shipper_id
    WHERE o.order_status = 'Delivered'
    GROUP BY s.shipper_id, s.company_name
)

SELECT 
    shipper_id,
    company_name,
    average_time,
    RANK() OVER (ORDER BY average_time ASC) AS rank_position
FROM avg_time
ORDER BY rank_position;



